'use client';
import { ChangeEvent, useEffect, useRef, useState } from 'react';

type Preset = 'viral-punch' | 'cinematic' | 'neon' | 'clean';
const presets: Record<Preset, { label:string; filter:string }> = {
  'viral-punch': { label:'Viral Punch', filter:'contrast(1.14) saturate(1.22) brightness(1.03)' },
  cinematic: { label:'Cinematic', filter:'contrast(1.08) saturate(0.92) brightness(0.96)' },
  neon: { label:'Neon Glow', filter:'contrast(1.18) saturate(1.35) brightness(1.05)' },
  clean: { label:'Clean HD', filter:'contrast(1.04) saturate(1.05) brightness(1.04)' },
};

export default function ImageStudio(){
 const canvasRef=useRef<HTMLCanvasElement>(null); const [file,setFile]=useState<File|null>(null); const [src,setSrc]=useState(''); const [preset,setPreset]=useState<Preset>('viral-punch'); const [scale,setScale]=useState(1); const [error,setError]=useState('');
 useEffect(()=>{if(!file){setSrc('');return;}const url=URL.createObjectURL(file);setSrc(url);return()=>URL.revokeObjectURL(url)},[file]);
 useEffect(()=>{if(!src)return;const image=new Image();image.onload=()=>{const canvas=canvasRef.current;if(!canvas)return;const max=4096;const ratio=Math.min(max/image.naturalWidth,max/image.naturalHeight,1)*scale;canvas.width=Math.max(1,Math.round(image.naturalWidth*ratio));canvas.height=Math.max(1,Math.round(image.naturalHeight*ratio));const ctx=canvas.getContext('2d');if(!ctx)return;ctx.filter=presets[preset].filter;ctx.drawImage(image,0,0,canvas.width,canvas.height);};image.src=src},[src,preset,scale]);
 function select(e:ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;if(!f.type.startsWith('image/'))return setError('Pilih file gambar.');if(f.size>50*1024*1024)return setError('Ukuran gambar maksimal 50 MB.');setError('');setFile(f);setScale(1)}
 function exportImage(){const canvas=canvasRef.current;if(!canvas)return;canvas.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`clippnow-${preset}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)},'image/png');}
 return <main className="min-h-screen bg-[#05070d] px-4 py-6 text-white sm:px-8"><div className="mx-auto max-w-6xl"><a href="/dashboard" className="text-xs font-bold text-slate-500">← Dashboard</a><div className="mt-6 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><section className="rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">Image Studio</div><h1 className="mt-2 text-3xl font-black">HD Visual Lab</h1>{!file?<label className="mt-6 flex min-h-[460px] cursor-pointer items-center justify-center rounded-2xl border-2 border-dashed border-white/10 text-center"><input type="file" accept="image/*" className="hidden" onChange={select}/><div><div className="text-5xl">✦</div><div className="mt-4 font-black">Upload gambar</div><div className="mt-2 text-xs text-slate-600">JPG, PNG, WebP • maksimal 50 MB</div></div></label>:<div className="mt-6 rounded-2xl bg-black p-4"><canvas ref={canvasRef} className="mx-auto max-h-[65vh] max-w-full object-contain"/></div>}</section><aside className="rounded-3xl border border-white/10 bg-white/[0.025] p-5"><div className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">Enhance</div><h2 className="mt-2 text-2xl font-black">Bikin gambar lebih hidup.</h2><div className="mt-6 grid grid-cols-2 gap-2">{(Object.keys(presets) as Preset[]).map(key=><button key={key} onClick={()=>setPreset(key)} className={`rounded-xl border px-3 py-3 text-xs font-black ${preset===key?'border-cyan-300 bg-cyan-300/10 text-cyan-200':'border-white/10 text-slate-500'}`}>{presets[key].label}</button>)}</div><label className="mt-6 block text-xs font-bold text-slate-500">Detail / scale <span className="float-right">{scale.toFixed(1)}×</span><input type="range" min="1" max="1.5" step="0.1" value={scale} onChange={e=>setScale(Number(e.target.value))} className="mt-3 w-full accent-cyan-300"/></label>{error&&<div className="mt-5 rounded-xl border border-rose-400/20 bg-rose-400/10 p-3 text-xs text-rose-300">{error}</div>}<button disabled={!file} onClick={exportImage} className="mt-7 w-full rounded-xl bg-cyan-300 px-4 py-3.5 text-sm font-black text-slate-950 disabled:opacity-40">Export HD PNG →</button><p className="mt-4 text-[10px] leading-5 text-slate-600">ClippNow mempertahankan ukuran kanvas tinggi dan mengekspor PNG berkualitas tinggi. Browser membatasi ukuran canvas, jadi resolusi maksimum menyesuaikan perangkat.</p></aside></div></div></main>;
}
