import Link from 'next/link';
import { landingExperience } from '@/lib/ui/marketing-experience';

const formats = [
  { label: '9:16', name: 'Shorts / Reels / TikTok', className: 'h-16 w-9' },
  { label: '1:1', name: 'Feed & social', className: 'h-14 w-14' },
  { label: '16:9', name: 'YouTube & landscape', className: 'h-10 w-16' },
];

export default function Home() {
  return (
    <main className="min-h-screen overflow-hidden bg-[#05070d] text-white selection:bg-cyan-300 selection:text-slate-950">
      <div className="pointer-events-none fixed inset-0 opacity-40 [background-image:linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] [background-size:64px_64px]" />
      <div className="pointer-events-none absolute -left-48 top-20 h-[32rem] w-[32rem] rounded-full bg-cyan-400/10 blur-[110px]" />
      <div className="pointer-events-none absolute right-[-10rem] top-[22rem] h-[34rem] w-[34rem] rounded-full bg-violet-500/10 blur-[120px]" />
      <nav className="relative mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8 lg:px-10">
        <Link href="/" className="flex items-center gap-3"><BrandMark /><span className="text-xl font-black tracking-tight">Vid<span className="text-cyan-300">klipral</span></span></Link>
        <div className="hidden items-center gap-7 text-sm font-semibold text-slate-500 md:flex"><Link href="#how" className="transition hover:text-white">Cara kerja</Link><Link href="/pricing" className="transition hover:text-white">Harga</Link></div>
        <div className="flex items-center gap-2"><Link href="/auth/login" className="rounded-xl px-3 py-2 text-xs font-black text-slate-400 hover:text-white sm:px-4">Masuk</Link><Link href="/auth/signup" className="rounded-xl bg-cyan-300 px-4 py-2.5 text-xs font-black text-slate-950 shadow-lg shadow-cyan-950/30 transition hover:bg-cyan-200">Mulai gratis</Link></div>
      </nav>
      <section className="relative mx-auto max-w-7xl px-5 pb-16 pt-10 sm:px-8 sm:pb-24 sm:pt-16 lg:px-10">
        <div className="grid items-center gap-12 lg:grid-cols-[.96fr_1.04fr]">
          <div>
            <div className="inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/[0.06] px-3 py-1.5 text-[10px] font-black uppercase tracking-[0.18em] text-cyan-200"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-cyan-300 shadow-[0_0_12px_rgba(103,232,249,.9)]" /> {landingExperience.visualLabel}</div>
            <h1 className="mt-7 max-w-3xl text-5xl font-black leading-[0.96] tracking-[-0.04em] sm:text-7xl lg:text-[5.8rem]">Satu video.<span className="block text-slate-500">Banyak momen.</span><span className="block bg-gradient-to-r from-cyan-200 via-cyan-300 to-violet-300 bg-clip-text text-transparent">Lebih banyak konten.</span></h1>
            <p className="mt-7 max-w-xl text-sm leading-7 text-slate-500 sm:text-base">{landingExperience.hero} Upload sekali, biarkan Vidklipral menyiapkan clip, subtitle, efek, dan output yang siap dipublikasikan.</p>
            <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/auth/signup" className="rounded-2xl bg-cyan-300 px-6 py-4 text-center text-sm font-black text-slate-950 shadow-xl shadow-cyan-950/30 transition hover:-translate-y-0.5 hover:bg-cyan-200">Buat Clip Viral Gratis →</Link><Link href="/pricing" className="rounded-2xl border border-white/10 bg-white/[0.03] px-6 py-4 text-center text-sm font-black text-white transition hover:bg-white/[0.06]">Lihat paket</Link></div>
            <div className="mt-7 flex flex-wrap gap-2 text-[10px] font-bold text-slate-600"><span className="rounded-full border border-white/10 px-3 py-1.5">500 MB / video</span><span className="rounded-full border border-white/10 px-3 py-1.5">9:16 · 1:1 · 16:9</span><span className="rounded-full border border-white/10 px-3 py-1.5">Storage privat</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-2xl">
            <div className="absolute -inset-8 rounded-[3rem] bg-cyan-300/[0.05] blur-3xl" />
            <div className="relative rounded-[2rem] border border-white/10 bg-white/[0.035] p-2 shadow-2xl shadow-black/50 backdrop-blur-xl sm:p-3">
              <div className="overflow-hidden rounded-[1.5rem] border border-white/10 bg-[#080b12]">
                <div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><div className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-rose-400" /><span className="h-2 w-2 rounded-full bg-amber-300" /><span className="h-2 w-2 rounded-full bg-emerald-300" /></div><span className="text-[9px] font-black uppercase tracking-[.2em] text-slate-600">vidklipral / viral engine</span><span className="rounded-full bg-emerald-300/10 px-2 py-1 text-[8px] font-black text-emerald-200">LIVE</span></div>
                <div className="grid gap-4 p-4 sm:grid-cols-[1fr_145px] sm:p-5">
                  <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-black"><div className="aspect-video bg-[radial-gradient(circle_at_28%_30%,rgba(34,211,238,.3),transparent_25%),radial-gradient(circle_at_75%_70%,rgba(139,92,246,.28),transparent_32%),linear-gradient(135deg,#0b1220,#05070d)] p-4 sm:p-5"><div className="flex h-full items-end justify-between rounded-xl border border-white/10 bg-black/20 p-4"><div><div className="text-[8px] font-black uppercase tracking-[.2em] text-cyan-200">Long video</div><div className="mt-2 text-lg font-black">Finding your best moment…</div><div className="mt-3 flex items-center gap-2 text-[9px] font-bold text-slate-400"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-cyan-300" /> AI analyzing hook, emotion & retention</div></div><div className="h-14 w-1 rounded-full bg-cyan-300/70 shadow-[0_0_24px_rgba(103,232,249,.6)]" /></div></div><div className="border-t border-white/10 p-3"><div className="mb-2 flex justify-between text-[8px] font-bold text-slate-600"><span>00:00</span><span>42:18</span></div><div className="relative h-2 overflow-hidden rounded-full bg-white/10"><div className="absolute left-[61%] h-full w-[13%] rounded-full bg-cyan-300 shadow-[0_0_16px_rgba(103,232,249,.7)]" /><div className="absolute left-[67%] top-[-3px] h-4 w-px bg-white" /></div></div></div>
                  <div className="rounded-2xl border border-cyan-300/20 bg-gradient-to-b from-cyan-300/[0.09] to-violet-400/[0.05] p-3"><div className="mx-auto flex aspect-[9/16] w-full items-end overflow-hidden rounded-xl border border-white/10 bg-[radial-gradient(circle_at_50%_25%,rgba(34,211,238,.28),transparent_25%),linear-gradient(160deg,#111827,#05070d)] p-3 shadow-lg"><div className="w-full rounded-lg border border-white/10 bg-black/40 p-2 backdrop-blur"><div className="text-[7px] font-black uppercase tracking-widest text-cyan-200">Viral clip • 00:27</div><div className="mt-2 text-[11px] font-black leading-tight">“Ini bagian yang bikin orang berhenti scroll.”</div><div className="mt-3 h-1 rounded-full bg-cyan-300/60" /></div></div><div className="mt-3 flex items-center justify-between"><span className="text-[8px] font-black text-slate-500">9:16 READY</span><span className="text-[8px] font-black text-emerald-200">+ HIGH HOOK</span></div></div>
                </div>
                <div className="grid grid-cols-4 gap-2 border-t border-white/10 p-4"><MiniStep n="01" label="Upload" active /><MiniStep n="02" label="AI pilih" active /><MiniStep n="03" label="Render" /><MiniStep n="04" label="Publish" /></div>
              </div>
            </div>
            <div className="absolute -bottom-5 -left-3 rounded-2xl border border-emerald-300/20 bg-[#0a100f]/95 px-4 py-3 shadow-xl backdrop-blur-xl sm:-left-8"><div className="text-[9px] font-black uppercase tracking-widest text-slate-600">Automatic workflow</div><div className="mt-1 text-xs font-black text-emerald-200">Upload → AI pilih momen → Render → Publish</div></div>
          </div>
        </div>
      </section>
      <section id="how" className="relative border-y border-white/10 bg-white/[0.018]"><div className="mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-20 lg:px-10"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><div className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">Cara kerja</div><h2 className="mt-3 text-3xl font-black tracking-tight sm:text-4xl">Bukan editor rumit. Cukup upload.</h2></div><p className="max-w-xl text-sm leading-6 text-slate-500">Vidklipral menangani bagian yang biasanya memakan waktu: mencari momen kuat, membuat subtitle, memberi treatment visual, lalu menyiapkan output.</p></div><div className="mt-9 grid gap-px overflow-hidden rounded-3xl border border-white/10 bg-white/10 md:grid-cols-4">{landingExperience.workflow.map((step, i) => <article key={step} className="bg-[#080b12] p-6 sm:p-7"><div className="text-xs font-black text-cyan-300">0{i + 1}</div><h3 className="mt-10 text-lg font-black">{step}</h3><p className="mt-2 text-xs leading-5 text-slate-600">{['Masukkan video panjang hingga 500 MB.','AI membaca transkrip dan sinyal hook untuk memilih bagian paling potensial.','Subtitle dan efek diterapkan ke output sosial.','Hasil siap diunduh atau diteruskan ke alur publikasi.'][i]}</p></article>)}</div></div></section>
      <section className="relative mx-auto max-w-7xl px-5 py-14 sm:px-8 sm:py-20 lg:px-10"><div className="grid gap-4 md:grid-cols-3">{formats.map((format) => <div key={format.label} className="rounded-3xl border border-white/10 bg-white/[0.025] p-6"><div className="flex h-24 items-center justify-center rounded-2xl bg-black/30"><div className={`rounded-md border border-cyan-300/50 bg-cyan-300/[0.04] shadow-[0_0_30px_rgba(34,211,238,.06)] ${format.className}`} /></div><div className="mt-4 text-xs font-black">{format.label}</div><div className="mt-1 text-[10px] leading-4 text-slate-600">{format.name}</div></div>)}</div><div className="mt-4 rounded-[2rem] border border-cyan-300/15 bg-gradient-to-br from-cyan-300/[0.08] via-white/[0.02] to-violet-400/[0.06] p-7 sm:p-10"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">Ready when you are</div><h2 className="mt-3 max-w-2xl text-3xl font-black tracking-tight sm:text-4xl">Mulai dengan 1 kredit trial.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Tanpa workflow manual yang panjang. Upload video dan biarkan AI memulai.</p></div><Link href="/auth/signup" className="rounded-2xl bg-cyan-300 px-6 py-4 text-center text-sm font-black text-slate-950 transition hover:bg-cyan-200">Buat akun gratis →</Link></div></div></section>
      <footer className="relative border-t border-white/10 px-5 py-7 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-xs text-slate-600 sm:flex-row"><span>Vidklipral © 2026</span><span>AI video in • viral-ready content out.</span></div></footer>
    </main>
  );
}
function MiniStep({ n, label, active = false }: { n: string; label: string; active?: boolean }) { return <div className={`rounded-xl border p-2 ${active ? 'border-cyan-300/20 bg-cyan-300/[0.05]' : 'border-white/10 bg-white/[0.02]'}`}><div className="text-[7px] font-black text-slate-600">{n}</div><div className={`mt-1 text-[9px] font-black ${active ? 'text-cyan-200' : 'text-slate-500'}`}>{label}</div></div>; }
function BrandMark() { return <span className="relative flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl bg-cyan-300 text-slate-950 shadow-lg shadow-cyan-950/30"><span className="absolute h-6 w-6 rounded-full border-[5px] border-slate-950" /><span className="absolute right-1.5 h-2.5 w-2.5 rotate-45 rounded-[2px] bg-cyan-300" /><span className="relative text-[9px] font-black">▶</span></span>; }
