'use client';

import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { authExperience } from '@/lib/ui/marketing-experience';

export default function LoginPage() {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [socialLoading, setSocialLoading] = useState('');
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setLoading(true); setError(''); const supabase = createClient(); const { error: signInError } = await supabase.auth.signInWithPassword({ email, password }); if (signInError) { setError('Email atau password tidak benar.'); setLoading(false); return; } window.location.href = '/dashboard'; }
  async function signInWithProvider(provider: 'google' | 'facebook') { setSocialLoading(provider); setError(''); const supabase = createClient(); const { error: oauthError } = await supabase.auth.signInWithOAuth({ provider, options: { redirectTo: `${window.location.origin}/auth/callback?next=/dashboard` } }); if (oauthError) { setError(`Login ${provider === 'google' ? 'Google' : 'Facebook'} belum tersedia. Aktifkan provider di Supabase Auth.`); setSocialLoading(''); } }
  function signInWithTikTok() { setError('Login TikTok sedang disiapkan sebagai OAuth khusus Vidklipral. Untuk keamanan, aktifkan provider TikTok terlebih dahulu.'); }
  return (
    <main className="min-h-screen bg-[#05070d] text-white lg:grid lg:grid-cols-[1.05fr_.95fr]">
      <section className="relative hidden overflow-hidden border-r border-white/10 p-10 lg:flex lg:flex-col lg:justify-between"><div className="pointer-events-none absolute -left-32 top-20 h-96 w-96 rounded-full bg-cyan-300/10 blur-[100px]" /><div className="pointer-events-none absolute right-0 bottom-0 h-80 w-80 rounded-full bg-violet-400/10 blur-[100px]" /><a href="/" className="relative flex items-center gap-3 text-xl font-black"><BrandMark /><span>Vid<span className="text-cyan-300">klipral</span></span></a><div className="relative max-w-xl"><div className="text-[10px] font-black uppercase tracking-[.2em] text-cyan-300">{authExperience.visualLabel}</div><h2 className="mt-5 text-5xl font-black leading-none tracking-[-.04em]">Video panjang masuk.<span className="block text-slate-500">Momen viral keluar.</span></h2><p className="mt-5 max-w-lg text-sm leading-6 text-slate-500">Masuk untuk melanjutkan workspace, menyimpan project, kredit, dan hasil render kamu.</p><div className="mt-8 rounded-[2rem] border border-white/10 bg-white/[.03] p-3"><div className="overflow-hidden rounded-[1.5rem] border border-white/10 bg-black"><div className="aspect-video bg-[radial-gradient(circle_at_30%_30%,rgba(34,211,238,.25),transparent_28%),radial-gradient(circle_at_75%_65%,rgba(139,92,246,.2),transparent_32%),linear-gradient(135deg,#101827,#05070d)] p-5"><div className="flex h-full items-end justify-between rounded-2xl border border-white/10 bg-black/20 p-5"><div><div className="text-[8px] font-black uppercase tracking-widest text-cyan-200">AI Viral Engine</div><div className="mt-2 text-xl font-black">Detect → Caption → Enhance</div><div className="mt-3 text-[9px] font-bold text-slate-500">One tap workflow for creators</div></div><div className="h-16 w-1 rounded-full bg-cyan-300 shadow-[0_0_24px_rgba(103,232,249,.7)]" /></div></div><div className="grid grid-cols-3 gap-2 border-t border-white/10 p-3"><div className="rounded-lg bg-cyan-300/10 p-2 text-[8px] font-black text-cyan-200">HOOK +92%</div><div className="rounded-lg bg-white/5 p-2 text-[8px] font-black text-slate-400">SUBTITLE AI</div><div className="rounded-lg bg-white/5 p-2 text-[8px] font-black text-slate-400">9:16 READY</div></div></div></div></div><div className="relative text-[10px] font-bold text-slate-600">Private projects • Fast workflow • Creator-first</div></section>
      <div className="flex min-h-screen items-center justify-center px-5 py-8 sm:px-8"><div className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[0.035] p-7 shadow-2xl shadow-black/30 sm:p-9"><a href="/" className="text-xl font-black lg:hidden">Vid<span className="text-cyan-300">klipral</span></a><div className="mt-8 text-[10px] font-black uppercase tracking-[0.2em] text-cyan-300">Creator access</div><h1 className="mt-3 text-3xl font-black tracking-tight">Masuk ke workspace</h1><p className="mt-3 text-sm leading-6 text-slate-500">Lanjutkan membuat clip dengan AI.</p><div className="mt-7 grid gap-3"><SocialButton label="Lanjut dengan Google" icon="G" loading={socialLoading === 'google'} disabled={Boolean(socialLoading)} onClick={() => signInWithProvider('google')} light /><SocialButton label="Lanjut dengan Facebook" icon="f" loading={socialLoading === 'facebook'} disabled={Boolean(socialLoading)} onClick={() => signInWithProvider('facebook')} facebook /><SocialButton label="Lanjut dengan TikTok" icon="♪" loading={false} disabled={Boolean(socialLoading)} onClick={signInWithTikTok} dark /></div><div className="my-6 flex items-center gap-3 text-[10px] font-black uppercase tracking-[0.18em] text-slate-600"><span className="h-px flex-1 bg-white/10" /> atau email <span className="h-px flex-1 bg-white/10" /></div><form onSubmit={submit} className="space-y-4"><label className="block"><span className="mb-2 block text-xs font-bold text-slate-400">Email</span><input required autoComplete="email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-cyan-300/60" /></label><label className="block"><span className="mb-2 block text-xs font-bold text-slate-400">Password</span><input required autoComplete="current-password" minLength={8} type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm outline-none focus:border-cyan-300/60" /></label><div className="-mt-1 text-right"><a href="/auth/forgot-password" className="text-xs font-bold text-cyan-300 hover:text-cyan-200">Lupa password?</a></div>{error && <p className="rounded-xl border border-rose-400/20 bg-rose-400/10 px-3 py-2 text-xs font-semibold leading-5 text-rose-300">{error}</p>}<button disabled={loading || Boolean(socialLoading)} className="w-full rounded-xl bg-cyan-300 px-4 py-3 text-sm font-black text-slate-950 transition hover:bg-cyan-200 disabled:opacity-50">{loading ? 'Memproses…' : 'Masuk dengan Email →'}</button></form><p className="mt-6 text-center text-xs text-slate-600">Belum punya akun? <a href="/auth/signup" className="font-bold text-cyan-300">Daftar gratis</a></p></div></div>
    </main>
  );
}
function SocialButton({ label, icon, loading, disabled, onClick, light, facebook, dark }: { label: string; icon: string; loading: boolean; disabled: boolean; onClick: () => void; light?: boolean; facebook?: boolean; dark?: boolean }) { return <button type="button" disabled={disabled} onClick={onClick} className={`flex w-full items-center justify-center gap-3 rounded-xl border px-4 py-3 text-sm font-black transition disabled:opacity-50 ${light ? 'border-white/10 bg-white text-slate-900 hover:bg-slate-100' : facebook ? 'border-[#1877F2]/40 bg-[#1877F2] text-white hover:brightness-110' : dark ? 'border-white/10 bg-black text-white hover:bg-black/80' : 'border-white/10 bg-white/5 text-white'}`}><span className="w-5 text-base font-black">{icon}</span>{loading ? 'Menghubungkan…' : label}</button>; }
function BrandMark() { return <span className="relative flex h-10 w-10 items-center justify-center overflow-hidden rounded-xl bg-cyan-300 text-slate-950 shadow-lg shadow-cyan-950/30"><span className="absolute h-6 w-6 rounded-full border-[5px] border-slate-950" /><span className="absolute right-1.5 h-2.5 w-2.5 rotate-45 rounded-[2px] bg-cyan-300" /><span className="relative text-[9px] font-black">▶</span></span>; }
